# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Anush Mohan
tagline:          'Resume'
description:      'Curriculum Vitae'
url:              ''

author:
  name:           'Anush Mohan'
  url:            
  email:          'anush.mohan@gmail.com'

# Custom vars
version:          1.0.0

github:
  link:           https://github.com/anushmohan

linkedin:
  link:           https://linkedin.com/in/anushmohan  

pdf_download:
    link:         './Anush_Mohan_resume.pdf'

    